version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - REPOSITORY_REPO=andmorefine/next-origin
      - REPOSITORY_URI=316224805545.dkr.ecr.ap-northeast-1.amazonaws.com
      - IMAGE_TAG=latest
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_REPO:$IMAGE_TAG .
      - docker tag $REPOSITORY_REPO:$IMAGE_TAG $REPOSITORY_URI/$REPOSITORY_REPO:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI/$REPOSITORY_REPO:$IMAGE_TAG
